package com.example.reg_app;

import javax.persistence.*;

@Entity
//to map with the table created in database
@Table(name = "users")
public class User {
    @Id // for primary key column
    @GeneratedValue(strategy = GenerationType.IDENTITY)//value of id will be automatically generated by the database
    private Long id;

    @Column(nullable = false,unique = true,length = 45)
    private String email;

    @Column(nullable = false,length = 64)
    private String password;

    @Column(nullable = false,length = 45)
    private String name;

    @Column(nullable = false,length = 45)
    private String surname;

    //for protection

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }
}
